language: python

python:
  - "3.6"
  - "3.7"

cache: pip

install:
  - pip install -r requirements.txt

script:
  - py.test -v .
  - pytest --cov=urdu_characters -v
  - codecov

notifications:
  slack: urduhack:HarNbK5WrXQbu9XuFLPsSFtM