language: python
matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: false

cache: pip

install:
  - pip install -r requirements.txt

script:
  - py.test -v .
  - pytest --cov=urdu_characters -v
  - codecov

notifications:
  slack: urduhack:HarNbK5WrXQbu9XuFLPsSFtM